# Generated by Django 6.0.2 on 2026-02-28 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animagen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='html_content', to='animagen.session')),
            ],
            options={
                'verbose_name': 'Session HTML',
                'verbose_name_plural': 'Session HTMLs',
                'ordering': ['-created_at'],
            },
        ),
    ]
