# Generated by Django 6.0.2 on 2026-03-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animagen', '0002_sessionhtml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='role',
        ),
    ]
